language: android

android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support

    - android-25

    - sys-img-armeabi-v7a-android-25

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

jdk: oraclejdk8

os:
  - linux

before_install:
  - chmod +x gradlew

# Let's try to build...
install:
  - ./gradlew clean build
  # - pip install codecov

script:
   # - ./gradlew build connectedCheck

after_success:
  # codecov
