---
project_identifier: toaster
api_key: 16f0482968dd5add5bb920997a892cdd
base_url: https://api.crowdin.com
base_path: /Users/mars3142/GDrive/Coding/github.com/mars3142/toaster
 
files:
  -
    source: '/app/src/main/res/values/strings*.xml'                                  # source files filter
    translation: '/app/src/main/res/values-%two_letters_code%/%original_file_name%'  # where translations live

  -
    source: '/app/src/main/play/en-US/listing/*.txt'
    translation: '/app/src/main/play/%locale%/listing/%original_file_name%'
  -
    source: '/app/src/main/play/en-US/*.txt'
    translation: '/app/src/main/play/%locale%/%original_file_name%'
